config/routes.rb
Log::Tracker::Engine.routes.draw do
  resources :apps
  resources :problems do
    put :resolve
  end
end

app/models/log/tracker/app.rb
module Log::Tracker
  class App < ApplicationRecord
    has_many :problems, inverse_of: :app, dependent: :destroy

    validates :name, presence: true, uniqueness: { allow_blank: true }
  end
end

app/models/log/tracker/application_record.rb
module Log
  module Tracker
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/log/tracker/problem.rb
module Log::Tracker
  class Problem < ApplicationRecord
    DEFAULT_APP_ID = 1

    belongs_to :app

    validates :environment, presence: true
    validates :last_notice_at, :first_notice_at, presence: true

    def self.notify(options = {})
      app_id = options[:app_id] || DEFAULT_APP_ID

      App.find(app_id).problems.create!(
        environment: Rails.env,
        messages: options[:messages],
        issue_type: options[:issue_type],
        where: options[:where]
      )
    end
  end
end

app/controllers/log/tracker/application_controller.rb
module Log
  module Tracker
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
    end
  end
end

app/controllers/log/tracker/apps_controller.rb
require_dependency "log/tracker/application_controller"

module Log::Tracker
  class AppsController < ApplicationController
    def index
      @apps = Log::Tracker::App.all
    end
  end
end

app/controllers/log/tracker/problems_controller.rb
require_dependency "log/tracker/application_controller"

module Log::Tracker
  class ProblemsController < ApplicationController

    def index
      @problems = Problem.all
    end

    def resolve
      problem = Problem.find(params[:problem_id])
      problem.resolved = true
      problem.touch(:resolved_at)
      problem.save
    end
  end
end

app/helpers/log/tracker/application_helper.rb
module Log
  module Tracker
    module ApplicationHelper

      def button_class(resolved)
        resolved ? "btn-success" : "btn-danger"
      end
    end
  end
end

app/views/layouts/log/tracker/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Log tracker</title>
  <%= stylesheet_link_tag    "log/tracker/application", media: "all" %>
  <%= javascript_include_tag "log/tracker/application" %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <nav class="navbar navbar-default" role="navigation">
          <div class="navbar-header">
             
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
               <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="#">Audit Logger</a>
          </div>
          
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to "Apps", apps_path %>
              </li>
              <li>
                <%= link_to "Errors", problems_path %>
              </li>
            </ul>
          </div>
        </nav>
        <%= yield %>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>

</body>
</html>

app/views/log/tracker/apps/index.html.erb
<% if @apps.none? %>
  <h1>No apps here. Please create one.</h1>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>
          #
        </th>
        <th>
          Name
        </th>
        <th>
          Errors
        </th>
      </tr>
    </thead>
    <tbody>
      <% @apps.each_with_index do |app, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= app.name %></td>
        <td><%= app.problems.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/log/tracker/problems/index.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Env</th>
      <th>Messages</th>
      <th>Where</th>
      <th>Resolved</th>
    </tr>
  </thead>
  <tbody>
    <% @problems.each_with_index do |problem, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= problem.environment %></td>
      <td><%= problem.messages %></td>
      <td><%= problem.where %></td>
      <td>
        <%= button_to "#{problem.resolved}", problem_resolve_path(problem), method: :put, class: "btn btn-xs #{button_class(problem.resolved)}" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>